#!/usr/bin/env python
import sys
import os
version_number = ""
keywords = ""
description = ""
print 'whatis("Version: ' + version_number + '")'
print 'whatis("Keywords: '+ keywords + '")'
print 'whatis("Description: ' + description + '")'

dirname = '.'

def walklevel(some_dir, level=1):
    some_dir = some_dir.rstrip(os.path.sep)
    assert os.path.isdir(some_dir)
    num_sep = some_dir.count(os.path.sep)
    for root, dirs, files in os.walk(some_dir):
        yield root, dirs, files
        num_sep_this = root.count(os.path.sep)
        if num_sep + level <= num_sep_this:
            del dirs[:]

for path,dirs,files in walklevel(dirname, 0):
    for d in dirs:
        if "lib" in d:
            print 'prepend_path("LD_LIBRARY_PATH", "' + os.path.join(os.path.abspath(path), d) + '")'
            print 'prepend_path("LIBRARY_PATH", "' + os.path.join(os.path.abspath(path), d) + '")'
            if os.path.exists(os.path.join(path,d,"pkgconfig")):
                print 'prepend_path("PKG_CONFIG_PATH"' + os.path.join(os.path.abspath(path), d, "pkgconfig") + '")'
        if "bin" in d:
            print 'prepend_path("PATH", "' + os.path.join(os.path.abspath(path), d) + '")'
        if "man" in d:
            print 'prepend_path("MANPATH", "' + os.path.join(os.path.abspath(path), d) + '")'
        if "share" in d:
            if os.path.exists(os.path.join(path, d, "man")):
                print 'prepend_path("MANPATH", "' + os.path.join(os.path.abspath(path), d, "man") + '")'
        if "include" in d:
            print 'prepend_path("CPATH", "' + os.path.join(os.path.abspath(path), d) + '")'
            print 'prepend_path("CPLUS_INCLUDE_PATH", "' + os.path.join(os.path.abspath(path), d) + '")'
